baseurl = "https://blog.ordinarius-fectum.net"
title = "engineering note"
copyright = "Copyright &copy; 2019 - Author Name"
canonifyurls = true
theme = "hugo-kiera"

paginate = 3

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true

disqusShortname = "engineeringnote"
googleAnalytics = "UA-158665323-1"

enableGitInfo = true

# Note: to disable a social network icon delete or comment out the corresponding line
[author]
    name = "Hideo Suzuki"
    github = "lupinthe14th"
    #gitlab = "username"
    #linkedin = "username"
    #facebook = "username"
    twitter = "hideosuzuki2"
    instagram = "lupinthe14th"
    #stackoverflow = "username"
    #youtube = "user/username" # or channel/channelname
    kaggle = "lupinthe14th"

[params]
    tagline = "Creative and technical writing notes for ordinary engineer."
    description = "Creative and technical writing notes for ordinary engineer."
    images = ["./images/ogp.jpeg"] #This is used for opengraph/twitter cards.
    customCSS = []  #Optional Customised CSS
    favicon = "favicon.ico"

# uncomment to enable the Tags link on the main toolbar
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags"
    weight = 1

# uncomment to enable the Categories link on the main toolbar
#   [[menu.main]]
#     identifier = "categories"
#     name = "Categories"
#     url = "/categories"
#     weight = 1

[markup.goldmark.renderer]
  unsafe = true
